  name: Deploy the production

  on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
  permissions:
    contents: write

  jobs:
    Build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '22.x'

        - name: Install dependencies
          run: npm install

        - name: Build the project
          run: npm run build

        - name: Deploy to production server with gh-pages
          uses: JamesIves/github-pages-deploy-action@v4.7.3
          with:
            branch: gh-pages
            folder: build
    Test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
                node-version: '22.x'

          - name: Install dependencies
            run: npm install

          - name: Run tests
            run: npm run test -- --watchAll=false


